In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from config import username, password

# Extract First Data Source

In [2]:
energy_data = pd.read_excel ("Data Files/emissions_region2018.xlsx",header=1)

In [3]:
energy_data.head()

,Year,Census Division and State,\nCarbon Dioxide (CO2)\n(Thousand Metric Tons),\nSulfur Dioxide (SO2)\n(Thousand Metric Tons),\nNitrogen Oxides (NOx)\n(Thousand Metric Tons),Generation (Thousand Megawatthours),Kilograms of CO2 per Megawatthour of Generation,Grams of\nSO2 per Megawatthour of Generation,Grams of\nNOx per Megawatthour of Generation
0,2018,New England,27317.399,12.171,25.345,105548.461,258.814,115.316,240.128
1,2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301
2,2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872
3,2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195
4,2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428

# Transform

In [4]:
state_dict = {'Connecticut' : 'New England',
'Maine' : 'New England',
'Massachusetts' : 'New England',
'New Hampshire' : 'New England',
'Rhode Island' : 'New England',
'Vermont' : 'New England',
'New Jersey' : 'Middle Atlantic',
'New York' : 'Middle Atlantic',
'Pennsylvania' : 'Middle Atlantic',
'Illinois' : 'East North Central',
'Indiana' : 'East North Central',
'Michigan' : 'East North Central',
'Ohio' : 'East North Central',
'Wisconsin' : 'East North Central',
'Iowa' : 'West North Central',
'Kansas' : 'West North Central',
'Minnesota' : 'West North Central',
'Missouri' : 'West North Central',
'Nebraska' : 'West North Central',
'North Dakota' : 'West North Central',
'South Dakota' : 'West North Central',
'Delaware' : 'South Atlantic',
'District of Columbia' : 'South Atlantic',
'Florida' : 'South Atlantic',
'Georgia' : 'South Atlantic',
'Maryland' : 'South Atlantic',
'North Carolina' : 'South Atlantic',
'South Carolina' : 'South Atlantic',
'Virginia' : 'South Atlantic',
'West Virginia' : 'South Atlantic',
'Alabama' : 'East South Central',
'Kentucky' : 'East South Central',
'Mississippi' : 'East South Central',
'Tennessee' : 'East South Central',
'Arkansas' : 'West South Central',
'Louisiana' : 'West South Central',
'Oklahoma' : 'West South Central',
'Texas' : 'West South Central',
'Arizona' : 'Mountain',
'Colorado' : 'Mountain',
'Idaho' : 'Mountain',
'Montana' : 'Mountain',
'Nevada' : 'Mountain',
'New Mexico' : 'Mountain',
'Utah' : 'Mountain',
'Wyoming' : 'Mountain',
'California' : 'Pacific Contiguous',
'Oregon' : 'Pacific Contiguous',
'Washington' : 'Pacific Contiguous',
'Alaska' : 'Pacific Noncontiguous',
'Hawaii' : 'Pacific Noncontiguous'}

In [5]:
energy_data["Region"] = None

In [6]:
for state, region in state_dict.items():
    energy_data['Region'] = np.where(energy_data['Census Division and State'] == state, region, energy_data['Region'])

In [7]:
energy_data.head(20)

,Year,Census Division and State,\nCarbon Dioxide (CO2)\n(Thousand Metric Tons),\nSulfur Dioxide (SO2)\n(Thousand Metric Tons),\nNitrogen Oxides (NOx)\n(Thousand Metric Tons),Generation (Thousand Megawatthours),Kilograms of CO2 per Megawatthour of Generation,Grams of\nSO2 per Megawatthour of Generation,Grams of\nNOx per Megawatthour of Generation,Region
0,2018,New England,27317.399,12.171,25.345,105548.461,258.814,115.316,240.128,None
1,2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301,New England
2,2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872,New England
3,2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195,New England
4,2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428,New England
5,2018,Rhode Island,3347.857,0.063,1.885,8375.257,399.732,7.570,225.058,New England
6,2018,Vermont,9.975,0.048,0.488,2178.915,4.578,21.858,223.882,New England
7,2018,Middle Atlantic,123878.859,80.966,86.277,422939.928,292.899,191.437,203.993,None
8,2018,New Jersey,18911.751,3.077,10.077,75033.600,252.044,41.010,134.303,Middle Atlantic
9,2018,New York,27936.384,10.764,28.933,132520.498,210.808,81.223,218.332,Middle Atlantic
10,2018,Pennsylvania,77030.724,67.126,47.266,215385.830,357.641,311.653,219.449,Middle Atlantic
11,2018,East North Central,345079.936,346.013,250.773,609421.539,566.242,567.772,411.494,None
12,2018,Illinois,72260.775,80.056,36.922,188003.357,384.359,425.821,196.391,East North Central
13,2018,Indiana,91553.529,62.812,74.905,113459.711,806.925,553.605,660.187,East North Central
14,2018,Michigan,61435.293,74.327,52.077,115837.095,530.359,641.655,449.571,East North Central
15,2018,Ohio,78051.141,105.522,60.602,126184.610,618.547,836.249,480.262,East North Central
16,2018,Wisconsin,41779.199,23.296,26.268,65936.767,633.625,353.307,398.381,East North Central
17,2018,West North Central,213155.950,249.148,176.195,350241.930,608.596,711.359,503.067,None
18,2018,Iowa,34252.878,33.782,28.795,63380.566,540.432,533.008,454.316,West North Central
19,2018,Kansas,23747.647,4.949,17.392,51710.214,459.245,95.713,336.338,West North Central

In [8]:
energy_dataclean = energy_data.dropna()
energy_dataclean.head()

,Year,Census Division and State,\nCarbon Dioxide (CO2)\n(Thousand Metric Tons),\nSulfur Dioxide (SO2)\n(Thousand Metric Tons),\nNitrogen Oxides (NOx)\n(Thousand Metric Tons),Generation (Thousand Megawatthours),Kilograms of CO2 per Megawatthour of Generation,Grams of\nSO2 per Megawatthour of Generation,Grams of\nNOx per Megawatthour of Generation,Region
1,2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301,New England
2,2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872,New England
3,2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195,New England
4,2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428,New England
5,2018,Rhode Island,3347.857,0.063,1.885,8375.257,399.732,7.570,225.058,New England

In [9]:
energydata_final = energy_dataclean.rename(columns={"Census Division and State":"State",
                                 "\nCarbon Dioxide (CO2)\n(Thousand Metric Tons)":"CO2_ThousandMetricTons",
                         "\nSulfur Dioxide (SO2)\n(Thousand Metric Tons)":"SO2_ThousandMetricTons",
                        "\nNitrogen Oxides (NOx)\n(Thousand Metric Tons)":"NOx_ThousandMetricTons",
                        "Generation (Thousand Megawatthours)":"Generation_Megawatthours",
                        "Kilograms of CO2 per Megawatthour of Generation":"CO2_Kilograms_per_Megawatthour",
                        "Grams of\nSO2 per Megawatthour of Generation":"SO2_Grams_per_Megawatthour",
                        "Grams of\nNOx per Megawatthour of Generation":"NOx_Grams_Per_megawatthour"})

In [10]:
energydata_final = energydata_final.set_index('Year')
pollution_df = energydata_final.copy()
pollution_df.head()

,State,CO2_ThousandMetricTons,SO2_ThousandMetricTons,NOx_ThousandMetricTons,Generation_Megawatthours,CO2_Kilograms_per_Megawatthour,SO2_Grams_per_Megawatthour,NOx_Grams_Per_megawatthour,Region
Year,,,,,,,,,
2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301,New England
2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872,New England
2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195,New England
2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428,New England
2018,Rhode Island,3347.857,0.063,1.885,8375.257,399.732,7.570,225.058,New England

# Extract Second Data Source

In [11]:
pollution_data = pd.read_csv('Data Files/Net_generation_for_all_sectors (3).csv', header = 4)
pollution_data = pollution_data.drop(columns = ['units', 'source key'])
pollution_data = pollution_data.set_index('description')

pollution_data

,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,Aug 2001,Sep 2001,Oct 2001,...,Sep 2019,Oct 2019,Nov 2019,Dec 2019,Jan 2020,Feb 2020,Mar 2020,Apr 2020,May 2020,Jun 2020
description,,,,,,,,,,,,,,,,,,,,,
Net generation for all sectors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States : all fuels (utility-scale),332493,282940,300707,278079,300492,327694,357614,370533,306929,294734,...,359545.0,321875.0,316672.0,337253.0,339320.0,316934.0,305779.0,274876.0,303434.0,352936.0
United States : coal,177287,149735,155269,140671,151593,162616,179060,183116,154158,148931,...,85918.0,66829.0,75560.0,72554.0,65170.0,56072.0,50586.0,40576.0,46488.0,65475.0
United States : petroleum liquids,17300,9626,10981,10237,9641,10997,10050,13235,6432,5573,...,942.0,955.0,911.0,961.0,934.0,749.0,704.0,624.0,694.0,849.0
United States : petroleum coke,812,716,752,627,749,825,992,994,911,961,...,638.0,198.0,339.0,409.0,687.0,452.0,708.0,626.0,632.0,827.0
United States : natural gas,42389,37967,44364,45843,50934,57603,73030,78410,60181,56376,...,150753.0,133667.0,117762.0,129342.0,132980.0,126024.0,123569.0,108138.0,116236.0,143247.0
United States : other gases,718,676,769,698,785,733,840,848,767,737,...,1139.0,997.0,1196.0,1136.0,1211.0,1234.0,1109.0,801.0,862.0,832.0
United States : nuclear,68707,61272,62141,56003,61512,68023,69166,68389,63378,60461,...,66064.0,62033.0,64125.0,73074.0,74204.0,65950.0,63997.0,59170.0,64338.0,67205.0
United States : conventional hydroelectric,18852,17473,20477,18013,19176,20728,18079,18914,15256,15235,...,16324.0,16292.0,20520.0,22206.0,24286.0,25077.0,22269.0,20771.0,29468.0,28621.0
United States : other renewables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States : wind,389,431,532,685,635,670,635,577,490,607,...,24385.0,28136.0,25603.0,27183.0,28403.0,29235.0,29483.0,29534.0,28180.0,30147.0
United States : all utility-scale solar,7,13,31,39,81,91,92,85,65,21,...,6752.0,6131.0,4377.0,3494.0,4555.0,5652.0,6314.0,8010.0,9742.0,9467.0
United States : geothermal,1229,1073,1190,1095,1071,1088,1179,1167,1139,1162,...,1384.0,1277.0,1112.0,1301.0,1255.0,1156.0,1490.0,1356.0,1421.0,1342.0
United States : biomass,4400,3793,4042,4008,3951,4116,4339,4464,4076,4261,...,4788.0,4647.0,4604.0,4996.0,4957.0,4615.0,4843.0,4524.0,4654.0,4403.0
United States : wood and wood-derived fuels,3191,2697,2853,2821,2740,2891,3053,3179,2874,3046,...,3282.0,3081.0,3107.0,3407.0,3349.0,3154.0,3223.0,2992.0,3103.0,2994.0
United States : other biomass,1209,1096,1189,1187,1211,1225,1286,1285,1201,1215,...,1506.0,1565.0,1497.0,1588.0,1609.0,1461.0,1620.0,1532.0,1550.0,1409.0
United States : hydro-electric pumped storage,-589,-707,-773,-796,-623,-774,-871,-715,-928,-615,...,-671.0,-373.0,-509.0,-529.0,-406.0,-247.0,-353.0,-325.0,-367.0,-499.0
United States : other,992,872,931,957,986,978,1022,1048,1004,1025,...,1128.0,1087.0,1070.0,1126.0,1084.0,966.0,1058.0,1072.0,1088.0,1020.0
United States : all solar,--,--,--,--,--,--,--,--,--,--,...,9968.0,8971.0,6608.0,5541.0,6848.0,8261.0,9723.0,11811.0,13987.0,13725.0
United States : small-scale solar photovoltaic,--,--,--,--,--,--,--,--,--,--,...,3216.0,2840.0,2232.0,2046.0,2293.0,2609.0,3409.0,3801.0,4245.0,4258.0
United States : all utility-scale solar,7,13,31,39,81,91,92,85,65,21,...,6752.0,6131.0,4377.0,3494.0,4555.0,5652.0,6314.0,8010.0,9742.0,9467.0

In [12]:
last_row = len(pollution_data) - 1
pollution_data = pollution_data.drop(pollution_data.index[last_row])

In [13]:
pollution_data

,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,Aug 2001,Sep 2001,Oct 2001,...,Sep 2019,Oct 2019,Nov 2019,Dec 2019,Jan 2020,Feb 2020,Mar 2020,Apr 2020,May 2020,Jun 2020
description,,,,,,,,,,,,,,,,,,,,,
Net generation for all sectors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States : all fuels (utility-scale),332493,282940,300707,278079,300492,327694,357614,370533,306929,294734,...,359545.0,321875.0,316672.0,337253.0,339320.0,316934.0,305779.0,274876.0,303434.0,352936.0
United States : coal,177287,149735,155269,140671,151593,162616,179060,183116,154158,148931,...,85918.0,66829.0,75560.0,72554.0,65170.0,56072.0,50586.0,40576.0,46488.0,65475.0
United States : petroleum liquids,17300,9626,10981,10237,9641,10997,10050,13235,6432,5573,...,942.0,955.0,911.0,961.0,934.0,749.0,704.0,624.0,694.0,849.0
United States : petroleum coke,812,716,752,627,749,825,992,994,911,961,...,638.0,198.0,339.0,409.0,687.0,452.0,708.0,626.0,632.0,827.0
United States : natural gas,42389,37967,44364,45843,50934,57603,73030,78410,60181,56376,...,150753.0,133667.0,117762.0,129342.0,132980.0,126024.0,123569.0,108138.0,116236.0,143247.0
United States : other gases,718,676,769,698,785,733,840,848,767,737,...,1139.0,997.0,1196.0,1136.0,1211.0,1234.0,1109.0,801.0,862.0,832.0
United States : nuclear,68707,61272,62141,56003,61512,68023,69166,68389,63378,60461,...,66064.0,62033.0,64125.0,73074.0,74204.0,65950.0,63997.0,59170.0,64338.0,67205.0
United States : conventional hydroelectric,18852,17473,20477,18013,19176,20728,18079,18914,15256,15235,...,16324.0,16292.0,20520.0,22206.0,24286.0,25077.0,22269.0,20771.0,29468.0,28621.0
United States : other renewables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States : wind,389,431,532,685,635,670,635,577,490,607,...,24385.0,28136.0,25603.0,27183.0,28403.0,29235.0,29483.0,29534.0,28180.0,30147.0
United States : geothermal,1229,1073,1190,1095,1071,1088,1179,1167,1139,1162,...,1384.0,1277.0,1112.0,1301.0,1255.0,1156.0,1490.0,1356.0,1421.0,1342.0
United States : biomass,4400,3793,4042,4008,3951,4116,4339,4464,4076,4261,...,4788.0,4647.0,4604.0,4996.0,4957.0,4615.0,4843.0,4524.0,4654.0,4403.0
United States : wood and wood-derived fuels,3191,2697,2853,2821,2740,2891,3053,3179,2874,3046,...,3282.0,3081.0,3107.0,3407.0,3349.0,3154.0,3223.0,2992.0,3103.0,2994.0
United States : other biomass,1209,1096,1189,1187,1211,1225,1286,1285,1201,1215,...,1506.0,1565.0,1497.0,1588.0,1609.0,1461.0,1620.0,1532.0,1550.0,1409.0
United States : hydro-electric pumped storage,-589,-707,-773,-796,-623,-774,-871,-715,-928,-615,...,-671.0,-373.0,-509.0,-529.0,-406.0,-247.0,-353.0,-325.0,-367.0,-499.0
United States : other,992,872,931,957,986,978,1022,1048,1004,1025,...,1128.0,1087.0,1070.0,1126.0,1084.0,966.0,1058.0,1072.0,1088.0,1020.0
United States : all solar,--,--,--,--,--,--,--,--,--,--,...,9968.0,8971.0,6608.0,5541.0,6848.0,8261.0,9723.0,11811.0,13987.0,13725.0
United States : small-scale solar photovoltaic,--,--,--,--,--,--,--,--,--,--,...,3216.0,2840.0,2232.0,2046.0,2293.0,2609.0,3409.0,3801.0,4245.0,4258.0

In [14]:
new_pollution_data = pollution_data.transpose()

In [15]:
new_pollution_data = new_pollution_data.drop(columns = ["Net generation for all sectors", 'United States', 'United States : other renewables'])

In [16]:
new_pollution_data.tail(10)

description,United States : all fuels (utility-scale),United States : coal,United States : petroleum liquids,United States : petroleum coke,United States : natural gas,United States : other gases,United States : nuclear,United States : conventional hydroelectric,United States : wind,United States : geothermal,United States : biomass,United States : wood and wood-derived fuels,United States : other biomass,United States : hydro-electric pumped storage,United States : other,United States : all solar,United States : small-scale solar photovoltaic
Sep 2019,359545,85918,942,638,150753,1139,66064,16324,24385,1384,4788,3282,1506,-671,1128,9968,3216
Oct 2019,321875,66829,955,198,133667,997,62033,16292,28136,1277,4647,3081,1565,-373,1087,8971,2840
Nov 2019,316672,75560,911,339,117762,1196,64125,20520,25603,1112,4604,3107,1497,-509,1070,6608,2232
Dec 2019,337253,72554,961,409,129342,1136,73074,22206,27183,1301,4996,3407,1588,-529,1126,5541,2046
Jan 2020,339320,65170,934,687,132980,1211,74204,24286,28403,1255,4957,3349,1609,-406,1084,6848,2293
Feb 2020,316934,56072,749,452,126024,1234,65950,25077,29235,1156,4615,3154,1461,-247,966,8261,2609
Mar 2020,305779,50586,704,708,123569,1109,63997,22269,29483,1490,4843,3223,1620,-353,1058,9723,3409
Apr 2020,274876,40576,624,626,108138,801,59170,20771,29534,1356,4524,2992,1532,-325,1072,11811,3801
May 2020,303434,46488,694,632,116236,862,64338,29468,28180,1421,4654,3103,1550,-367,1088,13987,4245
Jun 2020,352936,65475,849,827,143247,832,67205,28621,30147,1342,4403,2994,1409,-499,1020,13725,4258

In [17]:
pollution_data_final = new_pollution_data.rename(index = {'description':'date'}, columns = {
    'United States : all fuels (utility-scale)' : 'all_fuels',
    'United States : coal' : 'coal',
    'United States : petroleum liquids' : 'petroleum_liquid',
    'United States : petroleum coke' : 'petroleum_coke',
    'United States : natural gas' : 'natural_gas',
    'United States : other gases' : 'other_gases',
    'United States : nuclear' : 'nuclear',
    'United States : conventional hydroelectric' : 'conventional_hydroelectric',
    'United States : wind' : 'wind',
    'United States : all utility-scale solar' : 'all_solar_utility-scale',
    'United States : geothermal' : 'geothermal',
    'United States : biomass' : 'biomass',
    'United States : wood and wood-derived fuels' : 'wood_fuels',
    'United States : other biomass' : 'other_biomass',
    'United States : hydro-electric pumped storage' : 'hydro-electric_pump_storage',
    'United States : other' : 'other',
    'United States : all solar' : 'all_solar',
    'United States : small-scale solar photovoltaic' : 'small-scale_solar_photovoltaic'  
})

In [18]:
pollution_data_final = pollution_data_final.rename_axis('date')
pollution_data_final = pollution_data_final.rename_axis("", axis="columns")
pollution_data_final

,all_fuels,coal,petroleum_liquid,petroleum_coke,natural_gas,other_gases,nuclear,conventional_hydroelectric,wind,geothermal,biomass,wood_fuels,other_biomass,hydro-electric_pump_storage,other,all_solar,small-scale_solar_photovoltaic
date,,,,,,,,,,,,,,,,,
Jan 2001,332493,177287,17300,812,42389,718,68707,18852,389,1229,4400,3191,1209,-589,992,--,--
Feb 2001,282940,149735,9626,716,37967,676,61272,17473,431,1073,3793,2697,1096,-707,872,--,--
Mar 2001,300707,155269,10981,752,44364,769,62141,20477,532,1190,4042,2853,1189,-773,931,--,--
Apr 2001,278079,140671,10237,627,45843,698,56003,18013,685,1095,4008,2821,1187,-796,957,--,--
May 2001,300492,151593,9641,749,50934,785,61512,19176,635,1071,3951,2740,1211,-623,986,--,--
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Feb 2020,316934,56072,749,452,126024,1234,65950,25077,29235,1156,4615,3154,1461,-247,966,8261,2609
Mar 2020,305779,50586,704,708,123569,1109,63997,22269,29483,1490,4843,3223,1620,-353,1058,9723,3409
Apr 2020,274876,40576,624,626,108138,801,59170,20771,29534,1356,4524,2992,1532,-325,1072,11811,3801
May 2020,303434,46488,694,632,116236,862,64338,29468,28180,1421,4654,3103,1550,-367,1088,13987,4245
Jun 2020,352936,65475,849,827,143247,832,67205,28621,30147,1342,4403,2994,1409,-499,1020,13725,4258

In [19]:
pollution_data_final.index = pd.to_datetime(pollution_data_final.index)
energy_df = pollution_data_final.copy()

# Load

In [20]:
the_little_engine_that_could = create_engine(f'postgresql://{username}:{password}@localhost:5432/energy-pollution-ETL')

In [21]:
con = the_little_engine_that_could.connect()

In [22]:
energy_df.to_sql('energy', con, if_exists = 'append')

In [23]:
pollution_df.to_sql('pollution', con, if_exists='append')