In [1]:
import pandas as pd
import numpy as np

In [2]:
energy_data = pd.read_excel ("Data Files/emissions_region2018.xlsx",header=1)

In [3]:
energy_data.head()

,Year,Census Division and State,\nCarbon Dioxide (CO2)\n(Thousand Metric Tons),\nSulfur Dioxide (SO2)\n(Thousand Metric Tons),\nNitrogen Oxides (NOx)\n(Thousand Metric Tons),Generation (Thousand Megawatthours),Kilograms of CO2 per Megawatthour of Generation,Grams of\nSO2 per Megawatthour of Generation,Grams of\nNOx per Megawatthour of Generation
0,2018,New England,27317.399,12.171,25.345,105548.461,258.814,115.316,240.128
1,2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301
2,2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872
3,2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195
4,2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428

In [4]:
state_dict = {'Connecticut' : 'New England',
'Maine' : 'New England',
'Massachusetts' : 'New England',
'New Hampshire' : 'New England',
'Rhode Island' : 'New England',
'Vermont' : 'New England',
'New Jersey' : 'Middle Atlantic',
'New York' : 'Middle Atlantic',
'Pennsylvania' : 'Middle Atlantic',
'Illinois' : 'East North Central',
'Indiana' : 'East North Central',
'Michigan' : 'East North Central',
'Ohio' : 'East North Central',
'Wisconsin' : 'East North Central',
'Iowa' : 'West North Central',
'Kansas' : 'West North Central',
'Minnesota' : 'West North Central',
'Missouri' : 'West North Central',
'Nebraska' : 'West North Central',
'North Dakota' : 'West North Central',
'South Dakota' : 'West North Central',
'Delaware' : 'South Atlantic',
'District of Columbia' : 'South Atlantic',
'Florida' : 'South Atlantic',
'Georgia' : 'South Atlantic',
'Maryland' : 'South Atlantic',
'North Carolina' : 'South Atlantic',
'South Carolina' : 'South Atlantic',
'Virginia' : 'South Atlantic',
'West Virginia' : 'South Atlantic',
'Alabama' : 'East South Central',
'Kentucky' : 'East South Central',
'Mississippi' : 'East South Central',
'Tennessee' : 'East South Central',
'Arkansas' : 'West South Central',
'Louisiana' : 'West South Central',
'Oklahoma' : 'West South Central',
'Texas' : 'West South Central',
'Arizona' : 'Mountain',
'Colorado' : 'Mountain',
'Idaho' : 'Mountain',
'Montana' : 'Mountain',
'Nevada' : 'Mountain',
'New Mexico' : 'Mountain',
'Utah' : 'Mountain',
'Wyoming' : 'Mountain',
'California' : 'Pacific Contiguous',
'Oregon' : 'Pacific Contiguous',
'Washington' : 'Pacific Contiguous',
'Alaska' : 'Pacific Noncontiguous',
'Hawaii' : 'Pacific Noncontiguous'}

In [5]:
energy_data["Region"] = None

In [6]:
for state, region in state_dict.items():
    energy_data['Region'] = np.where(energy_data['Census Division and State'] == state, region, energy_data['Region'])

In [7]:
energy_data.head(20)

,Year,Census Division and State,\nCarbon Dioxide (CO2)\n(Thousand Metric Tons),\nSulfur Dioxide (SO2)\n(Thousand Metric Tons),\nNitrogen Oxides (NOx)\n(Thousand Metric Tons),Generation (Thousand Megawatthours),Kilograms of CO2 per Megawatthour of Generation,Grams of\nSO2 per Megawatthour of Generation,Grams of\nNOx per Megawatthour of Generation,Region
0,2018,New England,27317.399,12.171,25.345,105548.461,258.814,115.316,240.128,None
1,2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301,New England
2,2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872,New England
3,2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195,New England
4,2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428,New England
5,2018,Rhode Island,3347.857,0.063,1.885,8375.257,399.732,7.570,225.058,New England
6,2018,Vermont,9.975,0.048,0.488,2178.915,4.578,21.858,223.882,New England
7,2018,Middle Atlantic,123878.859,80.966,86.277,422939.928,292.899,191.437,203.993,None
8,2018,New Jersey,18911.751,3.077,10.077,75033.600,252.044,41.010,134.303,Middle Atlantic
9,2018,New York,27936.384,10.764,28.933,132520.498,210.808,81.223,218.332,Middle Atlantic
10,2018,Pennsylvania,77030.724,67.126,47.266,215385.830,357.641,311.653,219.449,Middle Atlantic
11,2018,East North Central,345079.936,346.013,250.773,609421.539,566.242,567.772,411.494,None
12,2018,Illinois,72260.775,80.056,36.922,188003.357,384.359,425.821,196.391,East North Central
13,2018,Indiana,91553.529,62.812,74.905,113459.711,806.925,553.605,660.187,East North Central
14,2018,Michigan,61435.293,74.327,52.077,115837.095,530.359,641.655,449.571,East North Central
15,2018,Ohio,78051.141,105.522,60.602,126184.610,618.547,836.249,480.262,East North Central
16,2018,Wisconsin,41779.199,23.296,26.268,65936.767,633.625,353.307,398.381,East North Central
17,2018,West North Central,213155.950,249.148,176.195,350241.930,608.596,711.359,503.067,None
18,2018,Iowa,34252.878,33.782,28.795,63380.566,540.432,533.008,454.316,West North Central
19,2018,Kansas,23747.647,4.949,17.392,51710.214,459.245,95.713,336.338,West North Central

In [8]:
energy_dataclean = energy_data.dropna()
energy_dataclean.head()

,Year,Census Division and State,\nCarbon Dioxide (CO2)\n(Thousand Metric Tons),\nSulfur Dioxide (SO2)\n(Thousand Metric Tons),\nNitrogen Oxides (NOx)\n(Thousand Metric Tons),Generation (Thousand Megawatthours),Kilograms of CO2 per Megawatthour of Generation,Grams of\nSO2 per Megawatthour of Generation,Grams of\nNOx per Megawatthour of Generation,Region
1,2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301,New England
2,2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872,New England
3,2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195,New England
4,2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428,New England
5,2018,Rhode Island,3347.857,0.063,1.885,8375.257,399.732,7.570,225.058,New England

In [19]:
energydata_final = energy_dataclean.rename(columns={"Census Division and State":"State",
                                 "\nCarbon Dioxide (CO2)\n(Thousand Metric Tons)":"CO2_ThousandMetricTons",
                         "\nSulfur Dioxide (SO2)\n(Thousand Metric Tons)":"SO2_ThousandMetricTons",
                        "\nNitrogen Oxides (NOx)\n(Thousand Metric Tons)":"NOx_ThousandMetricTons",
                        "Generation (Thousand Megawatthours)":"Generation_Megawatthours",
                        "Kilograms of CO2 per Megawatthour of Generation":"CO2_Kilograms_per_Megawatthour",
                        "Grams of\nSO2 per Megawatthour of Generation":"SO2_Grams_per_Megawatthour",
                        "Grams of\nNOx per Megawatthour of Generation":"NOx_Grams_Per_megawatthour"})

In [20]:
energydata_final.head()

,Year,State,CO2_ThousandMetricTons,SO2_ThousandMetricTons,NOx_ThousandMetricTons,Generation_Megawatthours,CO2_Kilograms_per_Megawatthour,SO2_Grams_per_Megawatthour,NOx_Grams_Per_megawatthour,Region
1,2018,Connecticut,9591.483,0.886,6.048,39453.552,243.108,22.449,153.301,New England
2,2018,Maine,2201.608,7.306,5.966,11280.700,195.166,647.635,528.872,New England
3,2018,Massachusetts,9975.913,2.519,8.456,27172.882,367.128,92.703,311.195,New England
4,2018,New Hampshire,2190.562,1.350,2.502,17087.156,128.199,79.004,146.428,New England
5,2018,Rhode Island,3347.857,0.063,1.885,8375.257,399.732,7.570,225.058,New England